name: build and sast
run-name: Build & SAST - from user @${{ github.actor }}

on: 
  workflow_dispatch:


jobs: 
  build:  
    runs-on: ubuntu-latests
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test
        
  sast:
    continue-on-error: true
    runs-on: ubuntu-latest
    
    steps:
      - name: CodeQL Bundle
        # You may pin to the exact commit or the version.
        # uses: advanced-security/codeql-bundle-action@9437ba7f33c2a978c8897fb21b2a7e0809199d20
        uses: advanced-security/codeql-bundle-action@v1.1.0
      
